// <auto-generated />
using System;
using GronkBowl.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GronkBowl.Infrastructure.Migrations
{
    [DbContext(typeof(GronkBowlDbContext))]
    [Migration("20260918004654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GronkBowl.Domain.CallSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefensiveSituationalPlays")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OffensiveSituationalPlays")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("Submitted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasRandomlyGenerated")
                        .HasColumnType("boolean");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("CallSheets");
                });

            modelBuilder.Entity("GronkBowl.Domain.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentRulesVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("GronkBowl.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventLog")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "Week");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("GronkBowl.Domain.Play", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Assignments")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefaultPlay")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPassPlay")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskProfile")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("GronkBowl.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArmorValue")
                        .HasColumnType("integer");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ChemistryModifier")
                        .HasColumnType("integer");

                    b.Property<string>("Contract")
                        .HasColumnType("jsonb");

                    b.Property<int>("Grit")
                        .HasColumnType("integer");

                    b.Property<string>("InjuryStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InjuryWeeksRemaining")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PermanentAttributePenalty")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Traits")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GronkBowl.Domain.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DraftOrder")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RulesVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Standings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("GronkBowl.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CapSpace")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<int>("MedicalFacilityLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Roster")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ScoutingFacilityLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PlayTeam", b =>
                {
                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("PlaybookId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayTeam");
                });

            modelBuilder.Entity("GronkBowl.Domain.CallSheet", b =>
                {
                    b.HasOne("GronkBowl.Domain.Team", null)
                        .WithOne("CurrentCallSheet")
                        .HasForeignKey("GronkBowl.Domain.CallSheet", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayTeam", b =>
                {
                    b.HasOne("GronkBowl.Domain.Play", null)
                        .WithMany()
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GronkBowl.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GronkBowl.Domain.Team", b =>
                {
                    b.Navigation("CurrentCallSheet");
                });
#pragma warning restore 612, 618
        }
    }
}
